name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build package
        run: yarn build

      - name: Create package
        run: |
          mkdir -p out
          yarn pack --filename out/interaction-toolkit.tgz

      - name: Extract changelog
        id: extract-changelog
        uses: dahlia/submark@5a5ff0a58382fb812616a5801402f5aef00f90ce
        with:
          input-file: CHANGELOG.md
          heading-level: 2
          heading-title-text: version ${{ github.ref_name }}
          ignore-case: true
          omit-heading: true

      - name: Display changelog
        run: 'cat ${{ steps.extract-changelog.outputs.output-file }}'

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ steps.extract-changelog.outputs.output-file }}
          generate_release_notes: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./out/*.tgz

      - name: Publish to NPM
        if: |
          github.event_name == 'push' &&
          (github.ref_type == 'tag' || github.ref == 'refs/heads/main')
        run: |
          set -ex
          npm config set //registry.npmjs.org/:_authToken "$NPM_AUTH_TOKEN"
          npm whoami
          if [[ "$GITHUB_REF_TYPE" = "tag" ]]; then
            npm publish --access public ./out/*.tgz
          else
            npm publish --access public --tag dev ./out/*.tgz
          fi
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
